This
NikulinProfi/JFD-Course pull request #13
Opened 2022-05-24 19:04 UTC by NikulinProfi

1 задание сделал

2022-05-25 08:02 UTC, Solexofficial commented on module1-lesson12/task1/task1.js
> +const student = {
всё отлично)

2022-05-25 08:03 UTC, Solexofficial commented on module1-lesson12/task2/task2.js
> +  switch (isDomestic) {
switch case тут излишен) isDomestic булево значение.
просто присваивай его this

2022-05-25 08:03 UTC, Solexofficial requested changes
12. task 2 нужно пересмотреть)

2022-05-27 04:52 UTC, NikulinProfi commented on module1-lesson12/task2/task2.js
> +  switch (isDomestic) {
Переделал задание

2022-06-01 21:03 UTC, merged